services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "7001:80"
    volumes:
      - ./laravel:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: posgres
    restart: always
    ports:
      - "7002:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: master
      POSTGRES_PASSWORD: password
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
